
CREATE TABLE stream (
    "id" serial PRIMARY KEY,
    "UNIXTIME" bigint NOT NULL,
    "side" VARCHAR,
    "size" NUMERIC,
    "price" NUMERIC,
    "priceChange" VARCHAR,
    "tradeID" VARCHAR,
    "blockTrade" BOOLEAN
);

CREATE TABLE basefeatures (
    "id" serial PRIMARY KEY,
    "UNIXTIME" bigint NOT NULL,
    "open" NUMERIC,
    "high" NUMERIC,
    "low" NUMERIC,
    "close" NUMERIC,
    "mean" NUMERIC,
    "VWMean" NUMERIC,
    "median" NUMERIC,
    "25%" NUMERIC,
    "50%" NUMERIC,
    "75%" NUMERIC,
    "center" NUMERIC,
    "buySideMean" NUMERIC,
    "sellSideMean" NUMERIC,
    "buySideVWMean" NUMERIC,
    "sellSideVWMean" NUMERIC,
    "buySideMedian" NUMERIC,
    "sellSideMedian" NUMERIC,
    "buySideCenter" NUMERIC,
    "sellSideCenter" NUMERIC,
    "buySide25%" NUMERIC,
    "buySide50%" NUMERIC,
    "buySide75%" NUMERIC,
    "sellSide25%" NUMERIC,
    "sellSide50%" NUMERIC,
    "sellSide75%" NUMERIC,
    "sideMean" NUMERIC,
    "sideMedian" NUMERIC,
    "priceChangeMean" NUMERIC,
    "opentime" NUMERIC,
    "closetime" NUMERIC,
    "time25%" NUMERIC,
    "time50%" NUMERIC,
    "time75%" NUMERIC,
    "reHighPrice" NUMERIC,
    "reLowPrice" NUMERIC,
    "reClosePrice" NUMERIC,
    "reMeanPrice" NUMERIC,
    "reMedianPrice" NUMERIC,
    "re25%Price" NUMERIC,
    "re50%Price" NUMERIC,
    "re75%Price" NUMERIC,
    "reCenterPrice" NUMERIC,
    "reHighCuSize" NUMERIC,
    "reLowCuSize" NUMERIC,
    "reCloseCuSize" NUMERIC,
    "reMeanCuSize" NUMERIC,
    "reMedianCuSize" NUMERIC,
    "re25%CuSize" NUMERIC,
    "re50%CuSize" NUMERIC,
    "re75%CuSize" NUMERIC,
    "reCenterCuSize" NUMERIC
);